import { config, library } from "@fortawesome/fontawesome-svg-core";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import {
  faPlus,
  faMinus,
  faAngleDown,
  faAngleRight,
  faAngleLeft,
  faCog,
  faAngleUp,
  faTrash,
  faEllipsisV,
  faAdjust,
  faSearch,
  faBars,
  faTimes,
  faList,
  faTh,
  faSun,
  faMoon,
  faExternalLinkAlt,
  faCircle,
  faRedo,
  faPoll,
  faPersonBooth,
  faInfo,
  faChartPie,
  faChair,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { faQuestionCircle } from "@fortawesome/free-regular-svg-icons";

config.autoAddCss = false;

library.add(
  faPlus,
  faMinus,
  faTrash,
  faRedo,
  faAngleDown,
  faAngleRight,
  faAngleLeft,
  faAngleUp,
  faCog,
  faEllipsisV,
  faGithub,
  faAdjust,
  faSearch,
  faBars,
  faTimes,
  faList,
  faTh,
  faSun,
  faMoon,
  faExternalLinkAlt,
  faQuestionCircle,
  faCircle,
  faPoll,
  faPersonBooth,
  faInfo,
  faChartPie,
  faChair,
  faUser
);
