backend:
  name: github
  repo: MMMalik/ilemandatow
  branch: dev

media_folder: static/img
public_folder: /img

collections:
  - name: "poll"
    identifier_field: "id"
    label: "Poll"
    folder: "content/polls"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Published At", name: "publishedAt", widget: "datetime" }
      - { label: "Published By", name: "publishedBy", widget: "string" }
      - { label: "Polled By", name: "polledBy", widget: "string" }
      - { label: "Poll Started At", name: "pollStartedAt", widget: "datetime" }
      - { label: "Poll Ended At", name: "pollEndedAt", widget: "datetime" }

  - name: "party"
    identifier_field: name
    label: "Party"
    folder: "content/parties"
    create: true
    extension: json
    slug: "{{name}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Abbreviation", name: "abbr", widget: "string" }
      - {
          label: "Parties",
          name: "parties",
          widget: "relation",
          collection: "party",
          value_field: "id",
          search_fields: ["name"],
          display_fields: ["name"],
        }
      - { label: "Logo", name: "logo", widget: "image" }
