backend:
  name: github
  repo: MMMalik/dev

media_folder: static/img
public_folder: /img

collections:
  - name: "poll"
    identifier_field: "id"
    label: "Poll"
    folder: "content/polls"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Published At", name: "publishedAt", widget: "datetime" }
      - { label: "Published By", name: "publishedBy", widget: "string" }
      - { label: "Polled By", name: "polledBy", widget: "string" }
      - { label: "Poll Started At", name: "pollStartedAt", widget: "datetime" }
      - { label: "Poll Ended At", name: "pollEndedAt", widget: "datetime" }

  - name: "party"
    label: "Party"
    folder: "content/parties"
    create: true
    slug: "index"
    path: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "media" }
