backend:
  name: github
  repo: MMMalik/ilemandatow
  branch: main

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "polls"
    identifier_field: id
    summary: "{{publishedAt}} / {{summary}}"
    sortable_fields: ["publishedAt"]
    label: "Polls"
    folder: "packages/content/polls"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - {
          label: "Published By",
          name: "publishedBy___NODE",
          widget: "relation",
          collection: "publishers",
          value_field: "id",
          search_fields: ["name"],
          display_fields: ["name"],
        }
      - {
          label: "Published At",
          name: "publishedAt",
          widget: "datetime",
          format: YYYY-MM-DD,
        }
      - {
          label: "Polled By",
          name: "polledBy___NODE",
          widget: "relation",
          collection: "pollCompanies",
          value_field: "id",
          search_fields: ["name"],
          display_fields: ["name"],
        }
      - {
          label: "Poll Started At",
          name: "pollStartedAt",
          widget: "datetime",
          format: YYYY-MM-DD,
          default: "",
        }
      - {
          label: "Poll Ended At",
          name: "pollEndedAt",
          widget: "datetime",
          format: YYYY-MM-DD,
          default: "",
        }
      - {
          label: "Method",
          name: "method",
          widget: "select",
          options: ["CATI", "CAWI", "Unknown"],
          default: ["Unknown"],
        }
      - { label: "Margin of error", name: "error", widget: "number" }
      - {
          label: "Participants Count",
          name: "participantsCount",
          widget: "number",
        }
      - {
          label: "Participants will vote",
          name: "participantsWillVote",
          widget: "number",
          value_type: "float",
          min: 0.0,
          max: 100.0,
          step: 1.0,
        }
      - {
          label: "Participants might vote",
          name: "participantsMightVote",
          widget: "number",
          value_type: "float",
          min: 0.0,
          max: 100.0,
          step: 1.0,
        }
      - {
          label: "Participants undecided",
          name: "participantsUndecided",
          widget: "number",
          value_type: "float",
          min: 0.0,
          max: 100.0,
          step: 1.0,
        }
      - {
          label: "Participants might not vote",
          name: "participantsMightNotVote",
          widget: "number",
          value_type: "float",
          min: 0.0,
          max: 100.0,
          step: 1.0,
        }
      - {
          label: "Participants will not vote",
          name: "participantsWillNotVote",
          widget: "number",
          value_type: "float",
          min: 0.0,
          max: 100.0,
          step: 1.0,
        }
      - {
          label: "Results",
          name: "results",
          widget: "list",
          fields:
            [
              {
                label: "Party",
                name: "party___NODE",
                widget: "relation",
                collection: "parties",
                value_field: "id",
                search_fields: ["name"],
                display_fields: ["name"],
              },
              {
                label: "Result",
                name: "result",
                widget: "number",
                value_type: "float",
                min: 0.0,
                max: 100.0,
                step: 1.0,
              },
            ],
        }

  - name: "parties"
    identifier_field: id
    label: "Parties"
    summary: "{{name}}"
    sortable_fields: ["name"]
    folder: "packages/content/parties"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Full Name", name: "fullName", widget: "string" }
      - { label: "Abbreviation", name: "abbr", widget: "string" }
      - { label: "Color", name: "color", widget: "color" }
      - {
          label: "Member Parties",
          name: "memberParties",
          widget: "list",
          default: [],
          fields:
            [
              {
                label: "Party",
                name: "party___NODE",
                widget: "relation",
                collection: "parties",
                value_field: "id",
                search_fields: ["name"],
                display_fields: ["name"],
              },
            ],
        }
      - { label: "Logo", name: "logo", widget: "image" }

  - name: "pollCompanies"
    identifier_field: id
    summary: "{{name}}"
    label: "Poll Companies"
    folder: "packages/content/pollCompanies"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Abbreviation", name: "abbr", widget: "string" }

  - name: "publishers"
    identifier_field: id
    summary: "{{name}}"
    label: "Publishers"
    folder: "packages/content/publishers"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "Id", name: "id", widget: "nanoid" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Abbreviation", name: "abbr", widget: "string" }
