export * from "./filterList";
export * from "./filterNonRegularParties";
export * from "./filterRegularParties";
export * from "./getDhondtResults";
export * from "./getElectoralCode";
export * from "./getLatestElectoralCode";
export * from "./getPartiesWithResults";
export * from "./getPartyColor";
// export * from "./groupDocs";
export * from "./sortByParliamentOrder";
export * from "./sortPollResults";
