#
# This workflow is responsible for merging changes from main branch to dev.
#

name: Cleanup after release

on:
  push:
    branches:
      # Production branch
      - main

jobs:
  cleanup-after-release:
    name: Cleanup after release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git remote set-branches origin '*'
          git fetch -v

      - name: Initialize git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Merge release branch to dev
        run: |
          git checkout dev
          git merge main
          git push
