#
# Workflow responsible for deploying to production environment. Triggered manually.
#

name: Deploy prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to deploy"
        required: true

jobs:
  deploy-prod:
    name: Deploy prod
    environment:
      name: production
      url: https://ilemandatow.pl
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Use fixed Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.2"

      - name: Deploy API to prod
        run: |
          MD_SSH_KEY="${{ secrets.MD_SSH_KEY }}" \
          MD_SSH_USER="${{ secrets.MD_SSH_USER }}" \
          MD_SSH_HOST="${{ secrets.MD_SSH_HOST }}" \
          MD_DOMAIN="${{ secrets.MD_DOMAIN }}" \
          DB_USER="${{ secrets.DB_USER }}" \
          DB_PASS="${{ secrets.DB_PASS }}" \
          DB_NAME="${{ secrets.DB_NAME }}" \
          DB_URI="${{ secrets.DB_URI }}" \
          COOKIE_SECRET="${{ secrets.COOKIE_SECRET }}" \
          ILEMANDATOW_API_URL="${{ secrets.ILEMANDATOW_API_URL }}" \
          GH_REPO="${{ secrets.GH_REPO }}" \
          GH_REPO_OWNER="${{ secrets.GH_REPO_OWNER }}" \
          GH_REPO_EVENT_TYPE="${{ secrets.GH_REPO_EVENT_TYPE }}" \
          GH_ACCESS_TOKEN="${{ secrets.GH_ACCESS_TOKEN }}" \
          bash ./.github/workflows/deploy-api.sh

      - name: Deploy site to prod
        run: |
          NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          NETLIFY_SITE_ID="${{ secrets.NETLIFY_SITE_ID }}" \
          ILEMANDATOW_ALLOW_ROBOTS="${{ secrets.ILEMANDATOW_ALLOW_ROBOTS }}" \
          ILEMANDATOW_API_URL="${{ secrets.ILEMANDATOW_API_URL }}" \
          ILEMANDATOW_SITE_URL="${{ secrets.ILEMANDATOW_SITE_URL }}" \
          bash ./.github/workflows/deploy-site.sh
