#
# This workflow is responsible for deploying to production environment.
# It is triggered manually by providing a tag.
#

name: Deploy prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to deploy"
        required: true

jobs:
  deploy-preprod:
    name: Deploy preprod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Deploy to preprod
        run: |
          ILEMANDATOW_ACTIVE_ENV=production
          MD_SSH_KEY="${{ secrets.MD_SSH_KEY }}" \
          MD_SSH_USER="${{ secrets.MD_SSH_USER }}" \
          MD_SSH_HOST="${{ secrets.MD_SSH_HOST }}" \
          MD_SSH_DOMAIN="${{ secrets.MD_SSH_DOMAIN_PROD }}" \
          NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          NETLIFY_SITE_ID="${{ secrets.NETLIFY_SITE_ID_PROD }}" \
          DB_USER="${{ secrets.DB_USER_PROD }}" \
          DB_PASS="${{ secrets.DB_PASS_PROD }}" \
          DB_NAME="${{ secrets.DB_NAME_PROD }}" \
          DB_URI="${{ secrets.DB_URI_PROD }}" \
          COOKIE_SECRET="${{ secrets.COOKIE_SECRET_PROD }}" \
          bash ./.github/workflows/deploy-app.sh
