#
# This workflow is responsible for deploying changes to release branches to development site on Netlify.
#

name: Deploy release branch changes

on:
  push:
    branches:
      # Release unique branch
      - release/*

jobs:
  deploy-dev:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - run: yarn install
      - run: yarn cross-env ILEMANDATOW_ACTIVE_ENV=development build

      - name: Deploy main site to netlify
        run: |
          yarn netlify deploy --dir=packages/site/public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
