#
# Workflow responsible for deploying content change to production environment.
# Triggered by events sent from CMS.
#

name: Deploy prod content

on:
  repository_dispatch:
    types: [deploy-prod-content]

jobs:
  deploy-prod-content:
    name: Deploy prod content
    environment:
      name: production
      url: https://ilemandatow.pl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: v${{ github.event.client_payload.version }}

      - name: Deploy site to prod
        run: |
          NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          NETLIFY_SITE_ID="${{ secrets.NETLIFY_SITE_ID }}" \
          ILEMANDATOW_ALLOW_ROBOTS="${{ secrets.ILEMANDATOW_ALLOW_ROBOTS }}" \
          ILEMANDATOW_API_URL="${{ secrets.ILEMANDATOW_API_URL }}" \
          ILEMANDATOW_SITE_URL="${{ secrets.ILEMANDATOW_SITE_URL }}" \          
          bash ./.github/workflows/deploy-site.sh
