#
# Workflow responsible for deploying to preprod environment. Runs after release package is created on `main` branch.
#

name: Deploy preprod

on:
  workflow_run:
    workflows: [Prod]
    branches: [main]
    types:
      - completed

jobs:
  deploy-preprod:
    name: Deploy preprod
    environment:
      name: preprod
      url: https://preprod.ilemandatow.pl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: set_lerna_json
        name: Set lerna json
        run: |
          content=`cat ./lerna.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=lernaJson::$content"

      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: v${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}

      - name: Deploy API to preprod
        run: |
          MD_SSH_KEY="${{ secrets.MD_SSH_KEY }}" \
          MD_SSH_USER="${{ secrets.MD_SSH_USER }}" \
          MD_SSH_HOST="${{ secrets.MD_SSH_HOST }}" \
          MD_DOMAIN="${{ secrets.MD_DOMAIN }}" \
          DB_USER="${{ secrets.DB_USER }}" \
          DB_PASS="${{ secrets.DB_PASS }}" \
          DB_NAME="${{ secrets.DB_NAME }}" \
          DB_URI="${{ secrets.DB_URI }}" \
          COOKIE_SECRET="${{ secrets.COOKIE_SECRET }}" \
          bash ./.github/workflows/deploy-api.sh

      - name: Deploy Site to preprod
        run: |
          NETLIFY_AUTH_TOKEN="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          NETLIFY_SITE_ID="${{ secrets.NETLIFY_SITE_ID }}" \
          bash ./.github/workflows/deploy-site.sh
