#
# This workflow is responsible for testing dev branch.
#

name: Dev

on:
  push:
    branches:
      # Default development branch
      - dev
    paths:
      # Trigger only for the following paths
      - packages/**

  pull_request:
    branches:
      - dev
    paths:
      - packages/**

jobs:
  deploy-dev:
    name: Dev
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use fixed Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.2"

      - name: Install dependencies
        run: yarn install

      # Skips build of main site since Gatsby build requires a running server
      - name: Build packages
        run: yarn build:api && yarn build:ui && yarn build:seats && yarn build:client

      - name: Run tests
        run: yarn test
