name: Development workflow

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      # Run yarn install, test and build
      - run: yarn install
      - run: yarn build
      - run: yarn test
