#
# Workflow responsible for preparing release branches.
#
# Main steps of this workflow:
# - bump version of the project with lerna
# - submit a PR for the new version
#

name: Prepare release

# Triggered manually via Github.
on: workflow_dispatch

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize git config
        run: |
          git config user.name "GitHub Action"
          git config user.email noreply@github.com

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Bump version via lerna
        run: npx lerna version prerelease --no-git-tag-version --conventional-commits --yes

      - id: set_lerna_json
        name: Set lerna json
        run: |
          content=`cat ./lerna.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=lernaJson::$content"

      - name: Create release branch
        run: |
          git checkout -b release/${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}

      - name: Commit versions
        run: |
          git add -A
          git commit --message "chore(release): prepare v${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}"

      - name: Push release branch
        run: |
          git push origin release/${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}

      - name: Create pull request to main for review
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}
          base: main
          title: Release version ${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
