#
# Workflow responsible for tagging changes merged to main branch.
#

name: Prod

on:
  push:
    branches:
      # Production branch
      - main

jobs:
  release-prod:
    name: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - id: set_lerna_json
        name: Set lerna json
        run: |
          content=`cat ./lerna.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=lernaJson::$content"

      - name: Create and push new tag
        run: |
          git tag -a v${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }} -m "chore(release) next release"
          git push --tags
