name: "Release prod"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "packages/content/**"

jobs:
  release-prod:
    name: "Finalize release and deploy prod"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - id: set_lerna_json
        name: Set lerna json
        run: |
          content=`cat ./lerna.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=lernaJson::$content"

      - name: Create and push new tag
        run: |
          git tag -a v${{ fromJson(steps.set_lerna_json.outputs.lernaJson).version }} -m "chore(release) next release"
          git push --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - run: yarn install
      - run: yarn build

      - name: Deploy main site to netlify
        run: |
          yarn netlify deploy --dir=packages/site/public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}

      - name: Deploy cms to netlify
        run: |
          yarn netlify deploy --dir=packages/cms/public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_CMS }}
