#
# This workflow is responsible for running tests, linters, etc. for PRs to dev.
#

name: Test PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Test PR to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - run: yarn install
      - run: yarn build
      - run: yarn test
